# -*- coding: utf-8 -*-
from __future__ import print_function
#import grequests
import json
import requests
import argparse

import re
import sys
reload(sys)
sys.setdefaultencoding('utf-8')


class Colors:
    BLUE        = '\033[94m'
    GREEN       = '\033[32m'
    RED         = '\033[0;31m'
    DEFAULT     = '\033[0m'
    ORANGE      = '\033[33m'
    WHITE       = '\033[97m'
    BOLD        = '\033[1m'
    BR_COLOUR   = '\033[1;37;40m'
banner = '''````````````````````````````````````````````````````````````````````````

                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                    ,NMMMMMMMN                                                                              
                                                                                                                                                                                                                  DMMMMMMMMMMMMM                                                                            
                                                                                                                                                                                                                  ~MMMZ,  :MMMMMM                                                                           
                                                                                                                                                                                                                   +=       NMMMM7                                                                          
                                                                                                                                                                                                                            7MMMMD                                                                          
                                                                                                                                                                                                                            :MMMMN                                                                          
       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM      NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                                          MMMMM+                                                                          
       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM      NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                                         ,MMMMM                                                                           
       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN      NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                                         MMMMM+                                                                           
       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN      NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                                       ,MMMMM:                                                                            
       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN      NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                      :MMMMM~                                                                             
       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN      NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                     +MMMMM,                                                                              
       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=       NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:          MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                   ~MMMMM+                                                                                
       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM?        NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ           MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                  $MMMMD                                                                                  
       ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,  8MMMMMMMMMMMMMMO         ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, MMMMMMMMMMMMMMM:            MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                                ,MMMMM+                                                                                   
                                     MMMMMMMMMMMMMMMI                                        MMMMMMMMMMMMMMM~             MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                               ~MMMMMMMMMMMMMMMM,                                                                         
                                    DMMMMMMMMMMMMMMZ                                        ZMMMMMMMMMMMMMMZ              MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                               =MMMMMMMMMMMMMMMM,                                                                         
                                   OMMMMMMMMMMMMMMD                                        MMMMMMMMMMMMMMMI               MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                                                                                                          
                                  MMMMMMMMMMMMMMM$                                        MMMMMMMMMMMMMMM=                MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                                                                                                          
                                 NMMMMMMMMMMMMMMO                                       ,MMMMMMMMMMMMMMM7,                MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                                                                                                          
                                NMMMMMMMMMMMMMM8                                        MMMMMMMMMMMMMMM+                  MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                                      DMMMM:                                                                              
                               DMMMMMMMMMMMMMMI                                        MMMMMMMMMMMMMMM$                   MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                                   ZMMMMMMM                                                                               
                              8MMMMMMMMMMMMMMM                                        MMMMMMMMMMMMMMM8                    MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                 MMMMMMMMMM                                                                               
                             OMMMMMMMMMMMMMMM                                        MMMMMMMMMMMMMMMO                     MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                 MMMM=MMMMM                                                                               
                            MMMMMMMMMMMMMMM+                                        MMMMMMMMMMMMMMM7                      MMMMMMMMMMMMMM                           8NMMMMMMMMMMMM:                                      MMMMM                                                                               
                           DMMMMMMMMMMMMMM8                                       ,MMMMMMMMMMMMMMM8                       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                      MMMMM                                                                               
                          8MMMMMMMMMMMMMMM                                        MMMMMMMMMMMMMMM,                        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                      MMMMM                                                                               
                         MMMMMMMMMMMMMMN7                                        MMMMMMMMMMMMMMMD                         MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                      MMMMM                                                                               
                        MMMMMMMMMMMMMMMD                                       :DMMMMMMMMMMMMMMN                          MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                      MMMMM                                                                               
                       $MMMMMMMMMMMMMMM                                        MMMMMMMMMMMMMMN7 ,,                        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                      MMMMM                                                                               
                      MMMMMMMMMMMMMMMO                                        MMMMMMMMMMMMMMM7                            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                      MMMMM                                                                               
                     MMMMMMMMMMMMMMMO                                       ?MMMMMMMMMMMMMMMN                             MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                      MMMMM                                                                               
                    NMMMMMMMMMMMMMMN                                       ,MMMMMMMMMMMMMMM?                              MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                      MMMMM                                                                               
                   MMMMMMMMMMMMMMMN                                        MMMMMMMMMMMMMMMO                               MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                      MMMMM                                                                               
                  MMMMMMMMMMMMMMMN                                       ,MMMMMMMMMMMMMMMM                                MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                                      MMMMM                                                                               
                 NMMMMMMMMMMMMMMM                                        MMMMMMMMMMMMMMMD                                 MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                                      MMMMM                                                                               
                MMMMMMMMMMMMMMMD                                        MMMMMMMMMMMMMMM$                                  MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                      MMMMM                                                                                                                                           
               MMMMMMMMMMMMMMMM                                       ~MMMMMMMMMMMMMMMM                                   MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                                                                                                          
              MMMMMMMMMMMMMMMM                                       :MMMMMMMMMMMMMMMZ                                    MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                                                                                                          
             MMMMMMMMMMMMMMMO                                       ,MMMMMMMMMMMMMMMD                                     MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                                                                                                          
            MMMMMMMMMMMMMMMM                                       ,MMMMMMMMMMMMMMMN                                      MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                 MMMMMMMMMMMMMMMMM                                                                        
           MMMMMMMMMMMMMMMM                                        MMMMMMMMMMMMMMMM                                       MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                 MMMMMMMMMMMMMMMMM                                                                        
          MMMMMMMMMMMMMMM$                                       :MMMMMMMMMMMMMMM8                                        MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                            NMMMM                                                                         
         MMMMMMMMMMMMMMMN                                       ~MMMMMMMMMMMMMMMN                                         MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                           :MMMM,                                                                         
       :DMMMMMMMMMMMMMMM                                       ,MMMMMMMMMMMMMMM$                                          MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                          ,MMMMN                                                                          
       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                          MMMMM                                                                           
      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8    +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                         IMMMMZ                                                                           
     MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8   ,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                                         MMMMD                                                                            
    +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8   IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                                        MMMMM                                                                             
    ?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8   ?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          MMMMMMMMMMMMMM                           DMMMMMMMMMMMMM:                                       MMMMM~                                                                             
    ?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8   ?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                                      ~MMMMM                                                                              
    ?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8   ?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                                      MMMMM                                                                               
    ?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8   ?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          MMMMMMMMMMMMMM                           8MMMMMMMMMMMMM:                                     OMMMM                                                                                
    ,+++++++++++++++++++++++++++++++++++++++++++++++++=+~   ,=+++++++++++++++++++++++++++++++++++++++++++++++++=          +++++++++++++=                           =+++++++++++++                                     ZMMMM8                                                                                
                                                                                                                                                                                                                     :MMMMM                                                                                 
                                                                                                                                                                                                                     MMMMM:                                                                                 
                                                                                                                                                                                                                    7MMMM+                                                                                  
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                             

  ````````````````````````````````````````````````````````````````````````````````             
[*]@zzh217
'''

#read csv

url='http://dir.twseo.org/ip-query3.php'
urll=raw_input('input domain:')
print(Colors.ORANGE+banner+Colors.DEFAULT)
datas = {'inputip':urll}
r = requests.post(url,data = datas)
req=r.content.decode('utf-8','ignore')
print(req)
matchObj = re.search('IP:.*?IP', req, re.M|re.I).group(0).replace('</font><br>IP','').replace('IP: <font color=#ff6600>','IP:')
matchObj2 = re.search(': <img.*?ISP', req, re.M|re.I).group(0).replace(': <img src="images/flags/tw.gif" height="12" width="18"> <font color=#ff6600>','region:').replace('</font><br>ISP','')
matchObj3 = re.search(u'\u4f86\u6e90:.*?IP', req, re.M|re.I).group(0).replace(u'\u4f86\u6e90'+': <font color=#ff6600>','ISP From:').replace('</font><br>IP','')
matchObj4 = re.search(u'\u5730\u7406:.*?\u7def', req, re.M|re.I).group(0).replace(u'\u5730\u7406: ','').replace('<font color=#ff6600>','').replace('</font> &nbsp;','').replace(u'\u7def','')
matchObj5 = re.search(u'\u7def\u5ea6:.*?\u7d93', req, re.M|re.I).group(0).replace(u'\u7def',u'\u7eac').replace('<font color=#ff6600>','').replace('</font> &nbsp;','').replace(u'\u7d93','')
matchObj6 = re.search(u'\u7d93\u5ea6:.*', req, re.M|re.I).group(0).replace(u'\u7d93',u'\u7ecf').replace('<font color=#ff6600>','').replace('</font><br></div>','')
print(matchObj)
print(matchObj2)
print(matchObj3)
print(matchObj4)
print(matchObj5)
print(matchObj6)
#print(req)
#print(r.status_code)